// Mission math: short themed problem sets that open inside each Bible mission. Each item says which level range
// it fits and which practice skill it matches, so "Follow school order" can skip topics the class has not reached.
import { P, N, FR, MX, USD, USD$, TM, W, S, DS, ri, pick, chance, shuffle, gcd, numChoices, prob } from './core.js';
import { gen as genSkill } from './skills.js';

const T = (lo, hi, skill, g) => ({ lo, hi, skill, g });
const eqs = (a, op, b, r, unit) => P(N(a), ' ', S(op), ' ', N(b), ' ', S('='), ' ', N(r), unit ? ' ' + unit : '', '.');
const fpOpts = (n, a, b) => { const w = []; for (let t = 0; t < 60 && w.length < 3; t++) { const x = ri(2, 9), y = Math.round(n / x) + pick([-1, 1]); if (y > 1 && x * y !== n && !w.some(q => q[0] === x && q[1] === y)) w.push([x, y]); } return shuffle([[a, b], ...w]).map(([x, y]) => W(x + ' rows of ' + y)); };
export const THEMES = {
  noah: { title: 'Ark math', lead: 'Noah needs help with numbers for the ark.', items: [
    T(5, 5, 'g4.fraceq', () => { return prob({ q: P('Eight people were on the ark: Noah, his wife, their 3 sons, and the sons’ 3 wives. What fraction of the people were Noah’s sons?'), vis: { t: 'fracbar', d: 8, a: 3 }, ans: FR(3, 8), choices: shuffle([FR(3, 8), FR(3, 5), FR(5, 8), FR(1, 3)]), data: { e: ['/', 3, 8] }, hint: P('How many people in all? How many were sons?'), steps: [P(N(3), ' sons out of ', N(8), ' people is ', FR(3, 8), '.')] }); }),
    T(5, 5, 'g4.fraccmp', () => { const [a, b] = pick([[3, 8], [5, 8], [2, 8], [6, 8]]); const v = a * 2 - b; return prob({ q: P('Noah’s family was ', FR(a, b), ' of the ark’s crew. Is ', FR(a, b), ' more than, less than, or equal to ', FR(1, 2), '?'), vis: { t: 'fracbars', bars: [[a, b], [1, 2]] }, ans: W(v > 0 ? 'more than' : v < 0 ? 'less than' : 'equal to'), choices: [W('more than'), W('less than'), W('equal to')], data: { cmp: [['/', a, b], ['/', 1, 2]] }, hint: P(FR(1, 2), ' is the same as ', FR(4, 8), '.'), steps: [P(FR(1, 2), ' ', S('='), ' ', FR(4, 8), '. ', FR(a, b), ' is ', v > 0 ? 'more than' : v < 0 ? 'less than' : 'equal to', ' ', FR(4, 8), '.')] }); }),
    T(5, 5, 'g4.factors', () => { const n = pick([12, 16, 18, 20, 24, 30, 36]); const fp = []; for (let a = 2; a * a <= n; a++) if (n % a === 0) fp.push([a, n / a]); const [a, b] = pick(fp); return prob({ q: P('Noah wants ', N(n), ' animals to stand in equal rows. Which way works?'), vis: { t: 'array', r: a, c: b, icon: 'sheep' }, ans: W(a + ' rows of ' + b), choices: fpOpts(n, a, b), data: { factorPair: n, rows: true }, hint: P('The rows times the animals in each row must make ', N(n), '.'), steps: [P(N(a), ' ', S('×'), ' ', N(b), ' ', S('='), ' ', N(n), '.')] }); }),
    T(0, 1, 'pk.count5', () => { const n = ri(2, 6); return prob({ q: P('Count the animals walking to the ark. How many?'), vis: { t: 'count', n, icon: pick(['sheep', 'cow']) }, ans: N(n), choices: numChoices(n, { n: 3, spread: 1 }), data: { count: n }, dots: true, hint: P('Touch each animal as you count.'), steps: [P('There are ', N(n), '.')] }); }),
    T(1, 3, 'g2.skip', () => { const p = ri(2, 9); return prob({ q: P('The animals came in pairs. A pair is 2. How many animals are in ', N(p), ' pairs?'), vis: { t: 'count', n: 2 * p, icon: 'sheep', pairs: true }, ans: N(2 * p), choices: numChoices(2 * p, { spread: 2, extra: [p, p + 2] }), num: true, data: { e: ['*', 2, p] }, hint: P('Count by twos: two, four, six...'), steps: [P(N(p), ' pairs is ', N(2 * p), ' animals.')] }); }),
    T(2, 3, 'g2.evenodd', () => { const n = ri(5, 20); return prob({ q: P('Can ', N(n), ' animals line up in pairs with none left over?'), vis: { t: 'count', n: Math.min(n, 20), icon: 'sheep', pairs: true }, ans: W(n % 2 ? 'No' : 'Yes'), choices: [W('Yes'), W('No')], data: { parity: n }, hint: P('Even numbers make pairs with none left over.'), steps: [P(N(n), ' is ', n % 2 ? 'odd, so one is left over.' : 'even, so every animal has a partner.')] }); }),
    T(4, 5, 'g3.mulfact', () => { const p = ri(3, 12); return prob({ q: P(N(p), ' pairs of animals went into the ark. How many animals is that?'), ans: N(2 * p), choices: numChoices(2 * p, { extra: [p + 2] }), num: true, data: { e: ['*', 2, p] }, hint: P('Each pair is 2 animals.'), steps: [eqs(p, '×', 2, 2 * p, 'animals')] }); }),
    T(4, 6, 'g4.areaperim', () => { const k = pick(['perimeter', 'area']); const L = 300, Wd = 50; const r = k === 'area' ? L * Wd : 2 * (L + Wd);
      return prob({ q: P('God told Noah to make the ark ', N(L), ' cubits long and ', N(Wd), ' cubits wide. What is the ', k, ' of the ark’s floor?'), vis: { t: 'area', w: 6, h: 1, label: 'cubits', labels: [L, Wd] }, ans: N(r), choices: numChoices(r, { extra: [k === 'area' ? 700 : 15000, L + Wd, L * 2] }), num: true, data: { e: k === 'area' ? ['*', L, Wd] : ['*', 2, ['+', L, Wd]] }, unit: k === 'area' ? 'square cubits' : 'cubits',
        hint: P(k === 'area' ? 'Area is length times width.' : 'Perimeter is all 4 sides added together.'), steps: [k === 'area' ? eqs(L, '×', Wd, r, 'square cubits') : P(N(L), ' ', S('+'), ' ', N(Wd), ' ', S('+'), ' ', N(L), ' ', S('+'), ' ', N(Wd), ' ', S('='), ' ', N(r), ' cubits.')] }); }),
    T(5, 5, 'g4.times', () => { const w = 50, k = 6; return prob({ q: P('The ark was ', N(w), ' cubits wide. It was ', N(k), ' times as long as it was wide. How long was it?'), vis: { t: 'tape', unit: w, times: k }, ans: N(w * k), choices: numChoices(w * k, { extra: [w + k, 250, 350] }), num: true, data: { e: ['*', w, k] }, hint: P('Times as long means multiply.'), steps: [eqs(w, '×', k, w * k, 'cubits')] }); }),
    T(5, 5, 'g4.convert', () => { const d = ri(2, 9); return prob({ q: P('It rained for many days. How many hours are in ', N(d), ' days?'), ans: N(d * 24), choices: numChoices(d * 24, { extra: [d * 12, d * 60] }), num: true, data: { e: ['*', d, 24] }, unit: 'hours', hint: P('1 day is 24 hours.'), steps: [eqs(d, '×', 24, d * 24, 'hours')] }); }),
    T(6, 9, 'g5.volume', () => { const r = 300 * 50 * 30; return prob({ q: P('The ark was ', N(300), ' cubits long, ', N(50), ' cubits wide, and ', N(30), ' cubits tall. If it were a box, what would its volume be in cubic cubits?'), ans: N(r), choices: numChoices(r, { extra: [45000, 4500, 380] }).map(x => x), num: true, data: { e: ['*', ['*', 300, 50], 30] }, unit: 'cubic cubits', hint: P('Volume is length times width times height.'), steps: [eqs(300, '×', 50, 15000), eqs(15000, '×', 30, r, 'cubic cubits')] }); }),
    T(7, 9, 'g6.ratio', () => { const s = ri(2, 6); return prob({ q: P('The ark was ', N(300), ' cubits long and ', N(50), ' cubits wide. A model ark is ', N(s), ' feet wide. How long is the model?'), ans: N(6 * s), choices: numChoices(6 * s, { extra: [s + 250, 300 / s].filter(Number.isInteger) }), num: true, data: { e: ['*', ['/', 300, 50], s] }, unit: 'feet', hint: P('The length is ', N(6), ' times the width.'), steps: [P(N(300), ' ', S('÷'), ' ', N(50), ' ', S('='), ' ', N(6), '.'), eqs(s, '×', 6, 6 * s, 'feet')] }); }),
  ] },
  david: { title: 'Stones and shapes', lead: 'David is sorting smooth stones. Can you help with the math?', items: [
    T(5, 5, 'g4.fraceq', () => { const g = pick([1, 2, 3, 4]); return prob({ q: P('David has ', N(5), ' stones. ', N(g), ' of them ', g === 1 ? 'is' : 'are', ' gray. ', FR(g, 5), ' of the stones are gray. Which fraction is equal to ', FR(g, 5), '?'), vis: { t: 'fracbars', bars: [[g, 5], [0, 10, '?/10']] }, ans: FR(2 * g, 10), choices: shuffle([FR(2 * g, 10), FR(g, 10), FR(2 * g + 1, 10), FR(2 * g + 2, 10)]), data: { e: ['/', g, 5] }, hint: P('Cut each fifth into 2 equal parts.'), steps: [P(FR(g, 5), ' ', S('='), ' ', FR(2 * g, 10), '.')] }); }),
    T(0, 0, 'pk.count5', () => { const n = ri(1, 5); return prob({ q: P('How many smooth stones?'), vis: { t: 'count', n, icon: 'stones' }, ans: N(n), choices: numChoices(n, { n: 3, spread: 1 }), data: { count: n }, dots: true, hint: P('Count each stone one time.'), steps: [P('There are ', N(n), ' stones.')] }); }),
    T(0, 1, 'pk.pattern', () => genSkill('pk.pattern')),
    T(1, 2, 'k.sub10', () => { const h = ri(1, 4); return prob({ q: P('David needs 5 stones. He has ', N(h), '. How many more does he need?'), vis: { t: 'tenframe', n: h, max: 5 }, ans: N(5 - h), choices: numChoices(5 - h, { n: 3, spread: 1 }), data: { e: ['-', 5, h] }, hint: P('Count up from ', N(h), ' to five.'), steps: [eqs(5, '−', h, 5 - h)] }); }),
    T(2, 4, 'g2.sides', () => genSkill(pick(['g2.sides', 'g3.quads']))),
    T(3, 4, 'g2.groups', () => { const b = ri(2, 5), n = ri(2, 5); return prob({ q: P('David puts ', N(n), ' stones in each of ', N(b), ' bags. How many stones is that?'), vis: { t: 'array', r: b, c: n, icon: 'stones' }, ans: N(b * n), choices: numChoices(b * n, { extra: [b + n] }), num: true, data: { e: ['*', b, n] }, hint: P('Count the equal groups.'), steps: [eqs(b, '×', n, b * n, 'stones')] }); }),
    T(5, 5, 'g4.multiple', () => { const k = pick([3, 4, 5, 6]), m = ri(3, 9); return prob({ q: P('David makes a pattern: he adds ', N(k), ' stones to each new row. Row 1 has ', N(k), ' stones. How many stones are in row ', N(m), '?'), vis: { t: 'rows', k, n: Math.min(m, 4) }, ans: N(k * m), choices: numChoices(k * m, { extra: [k + m, k * (m - 1)] }), num: true, data: { e: ['*', k, m] }, hint: P('The rows go ', N(k), ', ', N(2 * k), ', ', N(3 * k), '... They are multiples of ', N(k), '.'), steps: [eqs(k, '×', m, k * m, 'stones')] }); }),
    T(5, 5, 'g4.angletype', () => genSkill('g4.angletype')),
    T(5, 6, 'g4.lines', () => genSkill('g4.lines')),
    T(6, 9, 'g7.prob', () => genSkill('g7.prob')),
  ] },
  moses: { title: 'Mountain time', lead: 'Moses was on the mountain for 40 days. Let’s do some time and measuring math.', items: [
    T(5, 5, 'g4.prime', () => { const n = pick([12, 7, 40, 10, 5]); const pr = [7, 5].includes(n); const what = { 12: 'tribes of Israel', 7: 'days in a week', 40: 'days Moses was on the mountain', 10: 'commandments', 5: 'books of Moses' }[n]; return prob({ q: P('There are ', N(n), ' ', what, '. Is ', N(n), ' prime or composite?'), ans: W(pr ? 'prime' : 'composite'), choices: [W('prime'), W('composite')], data: { prime: n }, hint: P('A prime number has only one factor pair: 1 and itself.'), steps: [P(pr ? N(n) : N(n), pr ? ' has only one factor pair, so it is prime.' : ' has more than one factor pair, so it is composite.')] }); }),
    T(0, 1, 'pk.bigger', () => genSkill('pk.bigger')),
    T(1, 2, 'k.compareLen', () => genSkill('k.compareLen')),
    T(2, 3, 'g1.time', () => genSkill(pick(['g1.time', 'g2.time5']))),
    T(4, 4, 'g3.elapsed', () => genSkill('g3.elapsed')),
    T(4, 6, 'g4.div', () => { const d = 40; return prob({ q: P('Moses stayed on the mountain for ', N(d), ' days. How many full weeks is that, and how many extra days?'), ans: W('5 weeks and 5 days'), choices: shuffle([W('5 weeks and 5 days'), W('4 weeks and 12 days'), W('6 weeks and 2 days'), W('5 weeks and 3 days')]), data: { divrem: [40, 7] }, hint: P('A week has 7 days. How many sevens fit in forty?'), steps: [P(N(7), ' ', S('×'), ' ', N(5), ' ', S('='), ' ', N(35), '.'), P(N(40), ' ', S('−'), ' ', N(35), ' ', S('='), ' ', N(5), '. So 5 weeks and 5 days.')] }); }),
    T(5, 5, 'g4.convert', () => { const h = ri(2, 6); return prob({ q: P('Climbing the mountain took ', N(h), ' hours. How many minutes is that?'), ans: N(h * 60), choices: numChoices(h * 60, { extra: [h * 100, h * 24] }), num: true, data: { e: ['*', h, 60] }, unit: 'minutes', hint: P('1 hour is 60 minutes.'), steps: [eqs(h, '×', 60, h * 60, 'minutes')] }); }),
    T(5, 5, 'g4.convert', () => { const d = 40; return prob({ q: P('How many hours are in ', N(d), ' days?'), ans: N(d * 24), choices: numChoices(d * 24, { extra: [d * 12, d * 60, 64] }), num: true, data: { e: ['*', d, 24] }, unit: 'hours', hint: P('1 day is 24 hours. Try ', N(40), ' ', S('×'), ' ', N(20), ' plus ', N(40), ' ', S('×'), ' ', N(4), '.'), steps: [eqs(40, '×', 20, 800), eqs(40, '×', 4, 160), P(N(800), ' ', S('+'), ' ', N(160), ' ', S('='), ' ', N(960), ' hours.')] }); }),
    T(6, 9, 'g6.rate', () => genSkill(pick(['g6.rate', 'g7.scale']))),
  ] },
  samaritan: { title: 'Paying the innkeeper', lead: 'The Samaritan paid the innkeeper to care for the hurt man. Let’s count money.', items: [
    T(5, 5, 'g4.multiple', () => { const c = pick([75, 150, 200, 225, 130, 160, 110]); const yes = c % 25 === 0; return prob({ q: P('The innkeeper wants to be paid only in quarters. A quarter is ', USD(25), '. Can you pay exactly ', USD$(c), ' using only quarters?'), ans: W(yes ? 'Yes' : 'No'), choices: [W('Yes'), W('No')], data: { isMultiple: [c, 25] }, hint: P('Is ', N(c), ' a multiple of ', N(25), '? Count by 25s.'), steps: [yes ? P(N(c / 25), ' quarters make ', USD$(c), '.') : P(N(c), ' is not a multiple of ', N(25), '.')] }); }),
    T(5, 5, 'g4.fraceq', () => { const k = pick([1, 2, 3]); return prob({ q: P('A quarter is ', FR(1, 4), ' of a dollar. ', N(k), k === 1 ? ' quarter is' : ' quarters are', ' what fraction of a dollar in hundredths?'), vis: { t: 'grid100', a: 25 * k }, ans: FR(25 * k, 100), choices: shuffle([FR(25 * k, 100), FR(k, 100), FR(4 * k, 100), FR(25 * k + 25, 100)]), data: { e: ['/', k, 4] }, hint: P('One quarter is ', N(25), ' cents, and a dollar is ', N(100), ' cents.'), steps: [P(FR(k, 4), ' ', S('='), ' ', FR(25 * k, 100), '.')] }); }),
    T(0, 1, 'k.count20', () => { const n = ri(2, 8); return prob({ q: P('How many pennies?'), vis: { t: 'coins', coins: Array(n).fill(1) }, ans: N(n), choices: numChoices(n, { n: 3, spread: 1 }), data: { count: n }, dots: true, hint: P('Touch each penny as you count.'), steps: [P('There are ', N(n), ' pennies.')] }); }),
    T(2, 3, 'g2.coins', () => genSkill('g2.coins')),
    T(3, 4, 'g2.coins', () => { const nights = ri(2, 4), per = pick([25, 50, 75]); const r = nights * per; return prob({ q: P('A room at the inn costs ', USD(per), ' a night. How much for ', N(nights), ' nights?'), ans: USD$(r), choices: shuffle([r, r + 25, r - 25, per + nights].filter((x, i, a) => x > 0 && a.indexOf(x) === i)).map(USD$), data: { e: ['*', nights, per], cents: true }, hint: P('Add ', USD(per), ' for each night.'), steps: [P(N(nights), ' nights ', S('×'), ' ', USD(per), ' ', S('='), ' ', USD$(r), '.')] }); }),
    T(4, 6, 'g4.addsub', () => { const cost = ri(11, 79) * 5 + 100; const paid = 500; const r = paid - cost; return prob({ q: P('The Samaritan paid ', USD$(paid), ' for food and bandages that cost ', USD$(cost), '. How much change did he get?'), ans: USD$(r), choices: shuffle([...new Set([r, r + 10, r - 5 > 0 ? r - 5 : r + 15, r + 100])]).map(USD$), data: { e: ['-', paid, cost], cents: true }, hint: P('Subtract the cost from ', USD$(paid), '. Count up from ', USD$(cost), '.'), steps: [P(USD$(paid), ' ', S('−'), ' ', USD$(cost), ' ', S('='), ' ', USD$(r), '.')] }); }),
    T(5, 6, 'g4.mul1', () => { const per = ri(3, 9) * 100 + pick([0, 25, 50, 75]), d = ri(2, 6); return prob({ q: P('Care at the inn costs ', USD$(per), ' each day. How much for ', N(d), ' days?'), ans: USD$(per * d), choices: shuffle([...new Set([per * d, per * d + 100, per * d - 25, per + d * 100])]).map(USD$), data: { e: ['*', per, d], cents: true }, hint: P('Multiply the dollars, then the cents, then add.'), steps: [P(USD$(per), ' ', S('×'), ' ', N(d), ' ', S('='), ' ', USD$(per * d), '.')] }); }),
    T(7, 9, 'g7.pctchange', () => genSkill('g7.pctchange')),
  ] },
  loaves: { title: 'Sharing the bread', lead: 'Five loaves and two fish fed a huge crowd. Let’s do sharing math.', items: [
    T(0, 1, 'pk.join', () => { const a = ri(1, 3), b = ri(1, 2); return prob({ q: P('There ', a === 1 ? 'is ' : 'are ', N(a), a === 1 ? ' loaf and ' : ' loaves and ', N(b), b === 1 ? ' fish.' : ' fish.', ' How many things to eat in all?'), vis: { t: 'count2', a, b, icons: ['bread', 'fish'] }, ans: N(a + b), choices: numChoices(a + b, { n: 3, spread: 1 }), data: { e: ['+', a, b] }, dots: true, hint: P('Count them all together.'), steps: [P(N(a), ' and ', N(b), ' make ', N(a + b), '.')] }); }),
    T(1, 1, 'k.add10', () => { const r = 5 + 2; return prob({ q: P('The boy had ', N(5), ' loaves and ', N(2), ' fish. How many is that in all?'), vis: { t: 'count2', a: 5, b: 2, icons: ['bread', 'fish'] }, ans: N(r), choices: numChoices(r, { n: 3, spread: 1 }), data: { e: ['+', 5, 2] }, hint: P('Start at five and count on two.'), steps: [eqs(5, '+', 2, 7)] }); }),
    T(2, 3, 'g2.shares', () => genSkill(pick(['g1.halves', 'g2.shares']))),
    T(3, 4, 'g3.divfact', () => { const p = pick([2, 3, 4, 5, 6]), e = ri(2, 6); return prob({ q: P(N(p * e), ' pieces of bread are shared equally by ', N(p), ' people. How many pieces does each person get?'), vis: { t: 'share', n: p * e, groups: p, icon: 'bread' }, ans: N(e), choices: numChoices(e, { spread: 1 }), num: true, data: { e: ['/', p * e, p] }, hint: P('Deal them out one at a time, like cards.'), steps: [eqs(p * e, '÷', p, e, 'pieces each')] }); }),
    T(4, 5, 'g3.frac', () => { const d = pick([2, 3, 4, 6, 8]); const a = ri(1, d - 1); return prob({ q: P('A loaf is cut into ', N(d), ' equal pieces. ', N(a), ' ', a === 1 ? 'piece is' : 'pieces are', ' given away. What fraction of the loaf was given away?'), vis: { t: 'fracbar', d, a }, ans: FR(a, d), choices: shuffle([[a, d], [d - a, d], [a, d + 1], [d, a]].filter(([x, y], i, arr) => x < y && arr.findIndex(z => z[0] * y === z[1] * x) === i)).map(([x, y]) => FR(x, y)), data: { e: ['/', a, d] }, hint: P('The bottom number is how many equal pieces in the loaf.'), steps: [P(N(a), ' out of ', N(d), ' pieces is ', FR(a, d), '.')] }); }),
    T(5, 5, 'g4.fraccmp', () => { const [a, b, c, d] = pick([[1, 2, 2, 3], [3, 4, 2, 3], [2, 5, 1, 2], [5, 8, 3, 4], [2, 3, 5, 6], [3, 8, 1, 4]]); const bigger = a * d > c * b; return prob({ q: P('Andrew has ', FR(a, b), ' of a loaf. Philip has ', FR(c, d), ' of a loaf. The loaves are the same size. Who has more bread?'), vis: { t: 'fracbars', bars: [[a, b], [c, d]] }, ans: W(bigger ? 'Andrew' : 'Philip'), choices: [W('Andrew'), W('Philip')], data: { whoMore: [['/', a, b], ['/', c, d], 'Andrew', 'Philip'] }, hint: P('Rename both fractions with the same denominator, or compare them to one half.'), steps: [P(FR(a, b), ' ', S(bigger ? '>' : '<'), ' ', FR(c, d), ', so ', bigger ? 'Andrew' : 'Philip', ' has more.')] }); }),
    T(5, 5, 'g4.fracadd', () => { const d = pick([4, 6, 8]); const a = ri(1, d - 2), b = ri(1, d - 1 - a); return prob({ q: P('One family ate ', FR(a, d), ' of a loaf. Another family ate ', FR(b, d), ' of the same loaf. How much of the loaf did they eat in all?'), vis: { t: 'fracbars', bars: [[a, d], [b, d]] }, ans: FR(a + b, d), choices: shuffle([[a + b, d], [a + b, 2 * d], [a + b + 1, d], [a * b, d]].filter(([x, y], i, arr) => x > 0 && x <= y && arr.findIndex(z => z[0] === x && z[1] === y) === i)).map(([x, y]) => FR(x, y)), data: { e: ['+', ['/', a, d], ['/', b, d]], exactForm: true }, hint: P('Same denominators: add the tops.'), steps: [P(FR(a, d), ' ', S('+'), ' ', FR(b, d), ' ', S('='), ' ', FR(a + b, d), '.')] }); }),
    T(5, 6, 'g4.div', () => { const g = pick([50, 100]); const n = 5000; return prob({ q: P('About ', N(n), ' men sat down in groups of ', N(g), '. How many groups is that?'), ans: N(n / g), choices: numChoices(n / g, { extra: [n / g * 10, n / g / 10].filter(Number.isInteger) }), num: true, data: { e: ['/', n, g] }, hint: P('How many ', N(g), 's are in ', N(n), '? Think about ', N(n / 100), ' hundreds.'), steps: [eqs(n, '÷', g, n / g, 'groups')] }); }),
    T(5, 6, 'g4.mul1', () => { const b = 12, per = ri(12, 45); return prob({ q: P('After everyone ate, there were ', N(b), ' baskets of pieces left over. If each basket held ', N(per), ' pieces, how many pieces were left?'), vis: { t: 'areamodel', parts: [per - per % 10, per % 10].filter(Boolean), b }, ans: N(b * per), choices: numChoices(b * per, { extra: [b + per] }), num: true, data: { e: ['*', b, per] }, hint: P('Multiply ', N(per), ' by ', N(12), '. Try ', N(per), ' ', S('×'), ' ', N(10), ' plus ', N(per), ' ', S('×'), ' ', N(2), '.'), steps: [eqs(per, '×', 10, per * 10), eqs(per, '×', 2, per * 2), P(N(per * 10), ' ', S('+'), ' ', N(per * 2), ' ', S('='), ' ', N(per * 12), ' pieces.')] }); }),
    T(6, 9, 'g5.fracquot', () => genSkill('g5.fracquot')),
  ] },
  joseph: { title: 'Storehouse math', lead: 'Joseph stored grain for seven good years. Let’s count the sacks.', items: [
    T(5, 5, 'g4.fraceq', () => { const k = pick([2, 3, 4]); return prob({ q: P('There were ', N(7), ' good years and ', N(7), ' hungry years. What fraction of the ', N(14), ' years were good years? Pick the fraction equal to it.'), vis: { t: 'fracbars', bars: [[7, 14], [0, 2, '?']] }, ans: FR(1, 2), choices: shuffle([FR(1, 2), FR(1, 7), FR(7, 10), FR(2, 7)]), data: { e: ['/', 7, 14] }, hint: P(N(7), ' out of ', N(14), ' is ', FR(7, 14), '. Seven is half of fourteen.'), steps: [P(FR(7, 14), ' ', S('='), ' ', FR(1, 2), '.')] }); }),
    T(5, 5, 'g4.factors', () => { const n = pick([24, 36, 48, 60, 72]); const fp = []; for (let a = 2; a * a <= n; a++) if (n % a === 0 && n / a <= 12) fp.push([a, n / a]); const [a, b] = pick(fp); return prob({ q: P('Joseph stacks ', N(n), ' sacks in equal rows. Which way works?'), vis: { t: 'array', r: a, c: b, icon: 'grain' }, ans: W(a + ' rows of ' + b), choices: fpOpts(n, a, b), data: { factorPair: n, rows: true }, hint: P('Rows times sacks in each row must make ', N(n), '.'), steps: [P(N(a), ' ', S('×'), ' ', N(b), ' ', S('='), ' ', N(n), '.')] }); }),
    T(0, 1, 'pk.more', () => { let a = ri(1, 5), b = ri(1, 5); while (a === b) b = ri(1, 5); return prob({ q: P('Which pile has more sacks of grain?'), vis: { t: 'two', a, b, icon: 'grain' }, ans: W(a > b ? 'Group A' : 'Group B'), choices: [W('Group A'), W('Group B')], data: { more: [a, b] }, hint: P('Count each pile.'), steps: [P('Group A has ', N(a), '. Group B has ', N(b), '.')] }); }),
    T(1, 2, 'g1.add20', () => { const a = ri(3, 9), b = ri(2, 9); return prob({ q: P('Joseph has ', N(a), ' sacks. His helpers bring ', N(b), ' more. How many sacks now?'), vis: { t: 'tenframes', a, b }, ans: N(a + b), choices: numChoices(a + b, { spread: 1 }), num: true, data: { e: ['+', a, b] }, hint: P('Make a ten first.'), steps: [eqs(a, '+', b, a + b, 'sacks')] }); }),
    T(2, 3, 'g2.add100', () => { const a = ri(21, 60), b = ri(11, 39); return prob({ q: P('Year 1: ', N(a), ' sacks. Year 2: ', N(b), ' sacks. How many sacks in both years?'), ans: N(a + b), choices: numChoices(a + b, { extra: [a + b + 10, a + b - 10] }), num: true, data: { e: ['+', a, b] }, hint: P('Add the tens, then the ones.'), steps: [eqs(a, '+', b, a + b, 'sacks')] }); }),
    T(4, 4, 'g3.bargraph', () => genSkill('g3.bargraph')),
    T(4, 5, 'g3.mulfact', () => { const per = ri(3, 10); return prob({ q: P('Joseph stored ', N(per), ' big jars of grain each year for ', N(7), ' years. How many jars in all?'), ans: N(7 * per), choices: numChoices(7 * per, { extra: [7 + per, 6 * per] }), num: true, data: { e: ['*', 7, per] }, hint: P('Seven equal groups of ', N(per), '.'), steps: [eqs(7, '×', per, 7 * per, 'jars')] }); }),
    T(5, 5, 'g4.mul1', () => { const per = ri(120, 950); return prob({ q: P('Joseph stored ', N(per), ' sacks of grain each year for ', N(7), ' good years. How many sacks did he store?'), vis: { t: 'areamodel', parts: String(per).split('').map((d, i, a) => +d * 10 ** (a.length - 1 - i)).filter(Boolean), b: 7 }, ans: N(7 * per), choices: numChoices(7 * per, { extra: [7 + per, 7 * per + 100] }), num: true, data: { e: ['*', 7, per] }, hint: P('Break ', N(per), ' into hundreds, tens, and ones. Multiply each part by 7.'), steps: [eqs(per, '×', 7, 7 * per, 'sacks')] }); }),
    T(5, 5, 'g4.times', () => { const b = ri(3, 12), k = ri(2, 9); return prob({ q: P('One brother carried ', N(b), ' sacks. Joseph’s wagon carried ', N(k), ' times as many. How many sacks did the wagon carry?'), vis: { t: 'tape', unit: b, times: k }, ans: N(b * k), choices: numChoices(b * k, { extra: [b + k] }), num: true, data: { e: ['*', b, k] }, hint: P('Times as many means multiply.'), steps: [eqs(b, '×', k, b * k, 'sacks')] }); }),
    T(5, 5, 'g4.remwp', () => { const s = ri(25, 75), per = pick([4, 6, 8]); if (s % per === 0) return THEMES.joseph.items[7].g(); const q = Math.floor(s / per); return prob({ q: P('The brothers have ', N(s), ' sacks to carry. Each donkey can carry ', N(per), ' sacks. How many donkeys do they need to carry them all?'), ans: N(q + 1), choices: numChoices(q + 1, { spread: 1, extra: [q] }), num: true, data: { ceilDiv: [s, per] }, hint: P('Divide. If sacks are left over, one more donkey is needed.'), steps: [P(N(s), ' ', S('÷'), ' ', N(per), ' ', S('='), ' ', N(q), ' remainder ', N(s % per), '.'), P('So they need ', N(q + 1), ' donkeys.')] }); }),
    T(6, 9, 'g5.wp', () => genSkill('g5.wp')),
  ] },
  honesty: { title: 'Wall math', lead: 'Nehemiah is rebuilding the wall. Let’s measure the gap.', items: [
    T(5, 5, 'g4.factors', () => { const n = pick([18, 24, 30, 36, 40]); const fp = []; for (let a = 2; a * a <= n; a++) if (n % a === 0) fp.push([a, n / a]); const [a, b] = pick(fp); return prob({ q: P('A part of the wall uses ', N(n), ' stones in equal rows. Which way works?'), vis: { t: 'array', r: a, c: b, icon: 'stones' }, ans: W(a + ' rows of ' + b), choices: fpOpts(n, a, b), data: { factorPair: n, rows: true }, hint: P('Rows times stones in each row must make ', N(n), '.'), steps: [P(N(a), ' ', S('×'), ' ', N(b), ' ', S('='), ' ', N(n), '.')] }); }),
    T(5, 5, 'g4.fraccmp', () => { const [a, b, c, d] = pick([[2, 3, 3, 4], [1, 2, 3, 8], [3, 5, 1, 2], [5, 6, 3, 4]]); const v = a * d - c * b; return prob({ q: P('One team finished ', FR(a, b), ' of its part of the wall. Another team finished ', FR(c, d), ' of the same size part. Which team finished more?'), vis: { t: 'fracbars', bars: [[a, b], [c, d]] }, ans: W(v > 0 ? 'the first team' : 'the second team'), choices: [W('the first team'), W('the second team')], data: { whoMore: [['/', a, b], ['/', c, d], 'the first team', 'the second team'] }, hint: P('Rename both fractions with the same denominator.'), steps: [P(FR(a, b), ' ', S(v > 0 ? '>' : '<'), ' ', FR(c, d), '.')] }); }),
    T(0, 1, 'pk.count5', () => { const n = ri(2, 6); return prob({ q: P('How many blocks are in the wall?'), vis: { t: 'count', n, icon: 'stones' }, ans: N(n), choices: numChoices(n, { n: 3, spread: 1 }), data: { count: n }, dots: true, hint: P('Count each block.'), steps: [P('There are ', N(n), ' blocks.')] }); }),
    T(1, 3, 'g2.groups', () => { const r = 2, c = 3; return prob({ q: P('The gap in the wall is ', N(c), ' blocks long and ', N(r), ' blocks tall. How many blocks will fill it?'), vis: { t: 'array', r, c, icon: 'stones' }, ans: N(6), choices: numChoices(6, { n: 3, spread: 1, extra: [5] }), data: { e: ['*', 2, 3] }, hint: P('Count the rows: ', N(3), ' and ', N(3), ' more.'), steps: [eqs(3, '+', 3, 6, 'blocks')] }); }),
    T(2, 3, 'g2.length', () => genSkill('g2.length')),
    T(4, 4, 'g3.perim', () => genSkill('g3.perim')),
    T(4, 5, 'g3.area', () => { const c = 3, r = 2; return prob({ q: P('The gap is ', N(c), ' blocks long and ', N(r), ' blocks tall. What is its area in blocks?'), vis: { t: 'area', w: c, h: r, grid: true }, ans: N(6), choices: numChoices(6, { extra: [5, 10] }), num: true, data: { e: ['*', 3, 2] }, unit: 'blocks', hint: P('Rows times blocks in each row.'), steps: [eqs(2, '×', 3, 6, 'blocks')] }); }),
    T(5, 5, 'g4.convert', () => { const y = ri(3, 12); return prob({ q: P('One part of the wall is ', N(y), ' yards long. How many feet is that?'), ans: N(3 * y), choices: numChoices(3 * y, { extra: [12 * y, y + 3] }), num: true, data: { e: ['*', y, 3] }, unit: 'feet', hint: P('1 yard is 3 feet.'), steps: [eqs(y, '×', 3, 3 * y, 'feet')] }); }),
    T(5, 5, 'g4.areaperim', () => { const w = ri(12, 40), h = ri(6, 20); return prob({ q: P('A garden inside the city wall is a rectangle ', N(w), ' meters long and ', N(h), ' meters wide. A fence goes all the way around it. How long is the fence?'), vis: { t: 'area', w, h, grid: false, label: 'm' }, ans: N(2 * (w + h)), choices: numChoices(2 * (w + h), { extra: [w * h, w + h] }), num: true, data: { e: ['*', 2, ['+', w, h]] }, unit: 'meters', hint: P('Perimeter: add all 4 sides.'), steps: [P(N(w), ' ', S('+'), ' ', N(h), ' ', S('+'), ' ', N(w), ' ', S('+'), ' ', N(h), ' ', S('='), ' ', N(2 * (w + h)), ' meters.')] }); }),
    T(5, 5, 'g4.areaperim', () => { const w = ri(4, 12), A = w * ri(3, 9); return prob({ q: P('A part of the wall covers ', N(A), ' square feet. It is ', N(w), ' feet tall. How long is it?'), vis: { t: 'area', w: A / w, h: w, grid: false, label: 'ft', hideW: true }, ans: N(A / w), choices: numChoices(A / w, { extra: [A - w] }), num: true, data: { solve: [['*', w, 'x'], A] }, unit: 'feet', hint: P('Length times height is the area. What times ', N(w), ' is ', N(A), '?'), steps: [eqs(A, '÷', w, A / w, 'feet')] }); }),
    T(5, 6, 'g4.multistep', () => { const teams = ri(3, 8), per = ri(12, 30), done = ri(2, 20); const tot = teams * per; if (done >= tot) return THEMES.honesty.items[6].g(); return prob({ q: P(N(teams), ' teams each have ', N(per), ' stones to set in the wall. They have set ', N(done), ' stones so far. How many stones are left to set?'), ans: N(tot - done), choices: numChoices(tot - done, { extra: [tot, teams + per - done].filter(x => x > 0) }), num: true, data: { e: ['-', ['*', teams, per], done] }, hint: P('First find all the stones. Then subtract the ones already set.'), steps: [eqs(teams, '×', per, tot, 'stones'), eqs(tot, '−', done, tot - done, 'left')] }); }),
    T(6, 9, 'g7.scale', () => genSkill(pick(['g6.triarea', 'g7.scale']))),
  ] },
};
// Build a set of problems for a mission at a level. `allowed(skillId)` filters topics (school order).
export function themeSet(qid, lv, n = 3, allowed = () => true) {
  const th = THEMES[qid]; if (!th) return [];
  let pool = th.items.filter(it => lv >= it.lo && lv <= it.hi && allowed(it.skill));
  for (let d = 1; pool.length < 2 && d <= 9; d++) pool = th.items.filter(it => lv - d <= it.hi && lv >= it.lo - d && allowed(it.skill));
  if (!pool.length) pool = th.items.filter(it => it.lo <= lv) .slice(-2);
  const out = []; const bag = shuffle(pool);
  for (let i = 0; i < n; i++) { const it = bag[i % bag.length]; let p = null; for (let t = 0; t < 10 && !p; t++) { try { p = it.g(); } catch (e) { } } if (p) out.push({ ...p, id: p.id || it.skill, themeSkill: it.skill, theme: qid, lv }); }
  return out;
}
